
name: Automacao-ecommercer-EBAC-Shop
on:
  push:
    branches: [main]
    
jobs:
  testes:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true # se hover erro não parar a execução
        with:
          browser: chrome
