name: Automacao-ecommercer-EBAC-Shop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: npm install

    - name: Executar testes
      run: npm test

